# Site settings
title: Luan Tran
name: Luan Illustrates

# Build settings
host: 0.0.0.0
port: 3000
markdown: kramdown
permalink: pretty

gems: ["jemoji"]
sass:
  sass_dir: assets/css
  style: :nested

emoji_dir: assets/img/emoji

# Github pages
baseurl: /Luans-Portfolio
